/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.ActivityItem

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents a page object that wraps a list of issue activities. The main advantage of the page in comparision to a list of activities is cursors. The page provides boundary marks that allow continuous iteration over the activities from the place the page is finished.
 *
 * @param reverse 
 * @param beforeCursor 
 * @param afterCursor 
 * @param hasBefore 
 * @param hasAfter 
 * @param activities 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
open class ActivityCursorPage (

    @get:JsonProperty("reverse")
    val reverse: kotlin.Boolean? = null,
    @get:JsonProperty("beforeCursor")
    val beforeCursor: kotlin.String? = null,
    @get:JsonProperty("afterCursor")
    val afterCursor: kotlin.String? = null,
    @get:JsonProperty("hasBefore")
    val hasBefore: kotlin.Boolean? = null,
    @get:JsonProperty("hasAfter")
    val hasAfter: kotlin.Boolean? = null,
    @get:JsonProperty("activities")
    val activities: kotlin.collections.List<ActivityItem>? = null,
    @get:JsonProperty("id")
    val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String? = null,
)

