/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.AgileStatus
import online.ecm.youtrack.model.ColorCoding
import online.ecm.youtrack.model.ColumnSettings
import online.ecm.youtrack.model.CustomField
import online.ecm.youtrack.model.Project
import online.ecm.youtrack.model.Sprint
import online.ecm.youtrack.model.SprintsSettings
import online.ecm.youtrack.model.SwimlaneSettings
import online.ecm.youtrack.model.User
import online.ecm.youtrack.model.UserGroup

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents an agile board configuration.
 *
 * @param name 
 * @param owner 
 * @param visibleFor 
 * @param visibleForProjectBased 
 * @param updateableBy 
 * @param updateableByProjectBased 
 * @param orphansAtTheTop 
 * @param hideOrphansSwimlane 
 * @param estimationField 
 * @param originalEstimationField 
 * @param projects 
 * @param sprints 
 * @param currentSprint 
 * @param columnSettings 
 * @param swimlaneSettings 
 * @param sprintsSettings 
 * @param colorCoding 
 * @param status 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
interface Agile {

    @get:JsonProperty("name")
    val name: kotlin.String?
    @get:JsonProperty("owner")
    val owner: User?
    @get:JsonProperty("visibleFor")
    val visibleFor: UserGroup?
    @get:JsonProperty("visibleForProjectBased")
    val visibleForProjectBased: kotlin.Boolean?
    @get:JsonProperty("updateableBy")
    val updateableBy: UserGroup?
    @get:JsonProperty("updateableByProjectBased")
    val updateableByProjectBased: kotlin.Boolean?
    @get:JsonProperty("orphansAtTheTop")
    val orphansAtTheTop: kotlin.Boolean?
    @get:JsonProperty("hideOrphansSwimlane")
    val hideOrphansSwimlane: kotlin.Boolean?
    @get:JsonProperty("estimationField")
    val estimationField: CustomField?
    @get:JsonProperty("originalEstimationField")
    val originalEstimationField: CustomField?
    @get:JsonProperty("projects")
    val projects: kotlin.collections.List<Project>?
    @get:JsonProperty("sprints")
    val sprints: kotlin.collections.List<Sprint>?
    @get:JsonProperty("currentSprint")
    val currentSprint: Sprint?
    @get:JsonProperty("columnSettings")
    val columnSettings: ColumnSettings?
    @get:JsonProperty("swimlaneSettings")
    val swimlaneSettings: SwimlaneSettings?
    @get:JsonProperty("sprintsSettings")
    val sprintsSettings: SprintsSettings?
    @get:JsonProperty("colorCoding")
    val colorCoding: ColorCoding?
    @get:JsonProperty("status")
    val status: AgileStatus?
    @get:JsonProperty("id")
    val id: kotlin.String?
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String?
}

