/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.AgileColumnFieldValue
import online.ecm.youtrack.model.ColumnSettings
import online.ecm.youtrack.model.WIPLimit

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents settings for a single board column
 *
 * @param presentation 
 * @param isResolved 
 * @param ordinal 
 * @param parent 
 * @param wipLimit 
 * @param fieldValues 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
open class AgileColumn (

    @get:JsonProperty("presentation")
    val presentation: kotlin.String? = null,
    @get:JsonProperty("isResolved")
    val isResolved: kotlin.Boolean? = null,
    @get:JsonProperty("ordinal")
    val ordinal: kotlin.Int? = null,
    @get:JsonProperty("parent")
    val parent: ColumnSettings? = null,
    @get:JsonProperty("wipLimit")
    val wipLimit: WIPLimit? = null,
    @get:JsonProperty("fieldValues")
    val fieldValues: kotlin.collections.List<AgileColumnFieldValue>? = null,
    @get:JsonProperty("id")
    val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String? = null,
)

