/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.AttachmentActivityItemAllOf
import online.ecm.youtrack.model.CreatedDeletedActivityItem
import online.ecm.youtrack.model.IssueAttachment

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents a change in the list of attachments of an issue.
 *
 * @param id 
 * @param dollarType 
 * @param target 
 * @param removed 
 * @param added 
 */

data class AttachmentActivityItem (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("target")
    val target: IssueAttachment? = null,

    @field:JsonProperty("removed")
    val removed: kotlin.collections.List<IssueAttachment>? = null,

    @field:JsonProperty("added")
    val added: kotlin.collections.List<IssueAttachment>? = null

) : CreatedDeletedActivityItem(id, dollarType)

