/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.AttributeBasedSwimlaneSettingsAllOf
import online.ecm.youtrack.model.FilterField
import online.ecm.youtrack.model.SwimlaneEntityAttributeValue
import online.ecm.youtrack.model.SwimlaneSettings

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param enabled 
 * @param id 
 * @param dollarType 
 * @param `field` 
 * @param propertyValues 
 */

data class AttributeBasedSwimlaneSettings (

    @field:JsonProperty("enabled")
    override val enabled: kotlin.Boolean? = null,

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("field")
    val `field`: FilterField? = null,

    @field:JsonProperty("values")
    val propertyValues: kotlin.collections.List<SwimlaneEntityAttributeValue>? = null

) : SwimlaneSettings

