/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.Bundle
import online.ecm.youtrack.model.FieldStyle

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents a field value in YouTrack.
 *
 * @param name 
 * @param bundle 
 * @param description 
 * @param ordinal 
 * @param color 
 * @param hasRunningJob 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = BuildBundleElement::class, name = "BuildBundleElement"),
    JsonSubTypes.Type(value = EnumBundleElement::class, name = "EnumBundleElement"),
    JsonSubTypes.Type(value = LocalizableBundleElement::class, name = "LocalizableBundleElement"),
    JsonSubTypes.Type(value = OwnedBundleElement::class, name = "OwnedBundleElement"),
    JsonSubTypes.Type(value = StateBundleElement::class, name = "StateBundleElement"),
    JsonSubTypes.Type(value = VersionBundleElement::class, name = "VersionBundleElement")
)
interface BundleElement {

    @get:JsonProperty("name")
    val name: kotlin.String?
    @get:JsonProperty("bundle")
    val bundle: Bundle?
    @get:JsonProperty("description")
    val description: kotlin.String?
    @get:JsonProperty("ordinal")
    val ordinal: kotlin.Int?
    @get:JsonProperty("color")
    val color: FieldStyle?
    @get:JsonProperty("hasRunningJob")
    val hasRunningJob: kotlin.Boolean?
    @get:JsonProperty("id")
    val id: kotlin.String?
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String?
}

