/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents a set of custom field values in YouTrack.
 *
 * @param isUpdateable 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = BaseBundle::class, name = "BaseBundle"),
    JsonSubTypes.Type(value = BuildBundle::class, name = "BuildBundle"),
    JsonSubTypes.Type(value = EnumBundle::class, name = "EnumBundle"),
    JsonSubTypes.Type(value = OwnedBundle::class, name = "OwnedBundle"),
    JsonSubTypes.Type(value = StateBundle::class, name = "StateBundle"),
    JsonSubTypes.Type(value = UserBundle::class, name = "UserBundle"),
    JsonSubTypes.Type(value = VersionBundle::class, name = "VersionBundle")
)
interface Bundle {

    @get:JsonProperty("isUpdateable")
    val isUpdateable: kotlin.Boolean?
    @get:JsonProperty("id")
    val id: kotlin.String?
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String?
}

