/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.User
import online.ecm.youtrack.model.UserGroup

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param permittedGroups 
 * @param permittedUsers 
 */

data class CommandLimitedVisibilityAllOf (

    @field:JsonProperty("permittedGroups")
    val permittedGroups: kotlin.collections.List<UserGroup>? = null,

    @field:JsonProperty("permittedUsers")
    val permittedUsers: kotlin.collections.List<User>? = null

)

