/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.CustomFieldDefaults
import online.ecm.youtrack.model.FieldType
import online.ecm.youtrack.model.ProjectCustomField

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents a custom field in YouTrack.
 *
 * @param name 
 * @param localizedName 
 * @param fieldType 
 * @param isAutoAttached 
 * @param isDisplayedInIssueList 
 * @param ordinal 
 * @param aliases 
 * @param fieldDefaults 
 * @param hasRunningJob 
 * @param isUpdateable 
 * @param instances 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
open class CustomField (

    @get:JsonProperty("name")
    val name: kotlin.String? = null,
    @get:JsonProperty("localizedName")
    val localizedName: kotlin.String? = null,
    @get:JsonProperty("fieldType")
    val fieldType: FieldType? = null,
    @get:JsonProperty("isAutoAttached")
    val isAutoAttached: kotlin.Boolean? = null,
    @get:JsonProperty("isDisplayedInIssueList")
    val isDisplayedInIssueList: kotlin.Boolean? = null,
    @get:JsonProperty("ordinal")
    val ordinal: kotlin.Int? = null,
    @get:JsonProperty("aliases")
    val aliases: kotlin.String? = null,
    @get:JsonProperty("fieldDefaults")
    val fieldDefaults: CustomFieldDefaults? = null,
    @get:JsonProperty("hasRunningJob")
    val hasRunningJob: kotlin.Boolean? = null,
    @get:JsonProperty("isUpdateable")
    val isUpdateable: kotlin.Boolean? = null,
    @get:JsonProperty("instances")
    val instances: kotlin.collections.List<ProjectCustomField>? = null,
    @get:JsonProperty("id")
    val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String? = null,
)

