/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.CustomField
import online.ecm.youtrack.model.CustomFilterFieldAllOf
import online.ecm.youtrack.model.FilterField

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents a custom field of the issue.
 *
 * @param name 
 * @param id 
 * @param dollarType 
 * @param customField 
 */

data class CustomFilterField (

    @field:JsonProperty("name")
    override val name: kotlin.String? = null,

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("customField")
    val customField: CustomField? = null

) : FilterField

