/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.StorageEntry

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents email settings for this YouTrack installation.
 *
 * @param isEnabled 
 * @param host 
 * @param port 
 * @param mailProtocol 
 * @param anonymous 
 * @param login 
 * @param sslKey 
 * @param from 
 * @param replyTo 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
interface EmailSettings {

    @get:JsonProperty("isEnabled")
    val isEnabled: kotlin.Boolean?
    @get:JsonProperty("host")
    val host: kotlin.String?
    @get:JsonProperty("port")
    val port: kotlin.Int?
    @get:JsonProperty("mailProtocol")
    val mailProtocol: EmailSettings.MailProtocol?
    @get:JsonProperty("anonymous")
    val anonymous: kotlin.Boolean?
    @get:JsonProperty("login")
    val login: kotlin.String?
    @get:JsonProperty("sslKey")
    val sslKey: StorageEntry?
    @get:JsonProperty("from")
    val from: kotlin.String?
    @get:JsonProperty("replyTo")
    val replyTo: kotlin.String?
    @get:JsonProperty("id")
    val id: kotlin.String?
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String?
    /**
     * 
     *
     * Values: sMTP,sMTPS,sMTPTLS
     */
    enum class MailProtocol(val value: kotlin.String) {
        @JsonProperty(value = "SMTP") sMTP("SMTP"),
        @JsonProperty(value = "SMTPS") sMTPS("SMTPS"),
        @JsonProperty(value = "SMTP_TLS") sMTPTLS("SMTP_TLS");
    }
}

