/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.ColorCoding
import online.ecm.youtrack.model.CustomField
import online.ecm.youtrack.model.FieldBasedColorCodingAllOf

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Sets a card color based on a value of some custom field.
 *
 * @param id 
 * @param dollarType 
 * @param prototype 
 */

data class FieldBasedColorCoding (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("prototype")
    val prototype: CustomField? = null

) : ColorCoding

