/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.IssueResolvedActivityItemAllOf
import online.ecm.youtrack.model.SimpleValueActivityItem

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents an event when a user resolves an issue.
 *
 * @param id 
 * @param dollarType 
 * @param removed 
 * @param added 
 */

data class IssueResolvedActivityItem (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("removed")
    override val removed: kotlin.Long? = null,

    @field:JsonProperty("added")
    override val added: kotlin.Long? = null

) : SimpleValueActivityItem(id, dollarType, removed, added)

