/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.Issue
import online.ecm.youtrack.model.IssueComment
import online.ecm.youtrack.model.User
import online.ecm.youtrack.model.Visibility

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents a file that is attached to an issue or a comment.
 *
 * @param name 
 * @param author 
 * @param created 
 * @param updated 
 * @param propertySize 
 * @param extension 
 * @param charset 
 * @param mimeType 
 * @param metaData 
 * @param draft 
 * @param removed 
 * @param base64Content 
 * @param url 
 * @param visibility 
 * @param issue 
 * @param comment 
 * @param thumbnailURL 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
open class IssueAttachment (

    @get:JsonProperty("name")
    val name: kotlin.String? = null,
    @get:JsonProperty("author")
    val author: User? = null,
    @get:JsonProperty("created")
    val created: kotlin.Long? = null,
    @get:JsonProperty("updated")
    val updated: kotlin.Long? = null,
    @get:JsonProperty("size")
    val propertySize: kotlin.Long? = null,
    @get:JsonProperty("extension")
    val extension: kotlin.String? = null,
    @get:JsonProperty("charset")
    val charset: kotlin.String? = null,
    @get:JsonProperty("mimeType")
    val mimeType: kotlin.String? = null,
    @get:JsonProperty("metaData")
    val metaData: kotlin.String? = null,
    @get:JsonProperty("draft")
    val draft: kotlin.Boolean? = null,
    @get:JsonProperty("removed")
    val removed: kotlin.Boolean? = null,
    @get:JsonProperty("base64Content")
    val base64Content: kotlin.String? = null,
    @get:JsonProperty("url")
    val url: kotlin.String? = null,
    @get:JsonProperty("visibility")
    val visibility: Visibility? = null,
    @get:JsonProperty("issue")
    val issue: Issue? = null,
    @get:JsonProperty("comment")
    val comment: IssueComment? = null,
    @get:JsonProperty("thumbnailURL")
    val thumbnailURL: kotlin.String? = null,
    @get:JsonProperty("id")
    val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String? = null,
)

