/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.FieldStyle
import online.ecm.youtrack.model.Issue

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param issues 
 * @param color 
 * @param untagOnResolve 
 */

data class IssueTagAllOf (

    @field:JsonProperty("issues")
    val issues: kotlin.collections.List<Issue>? = null,

    @field:JsonProperty("color")
    val color: FieldStyle? = null,

    @field:JsonProperty("untagOnResolve")
    val untagOnResolve: kotlin.Boolean? = null

)

