/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.DurationValue
import online.ecm.youtrack.model.Issue
import online.ecm.youtrack.model.User
import online.ecm.youtrack.model.WorkItemType

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents a work item in an issue.
 *
 * @param author 
 * @param creator 
 * @param text 
 * @param textPreview 
 * @param type 
 * @param created 
 * @param updated 
 * @param duration 
 * @param date 
 * @param issue 
 * @param usesMarkdown 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
open class IssueWorkItem (

    @get:JsonProperty("author")
    val author: User? = null,
    @get:JsonProperty("creator")
    val creator: User? = null,
    @get:JsonProperty("text")
    val text: kotlin.String? = null,
    @get:JsonProperty("textPreview")
    val textPreview: kotlin.String? = null,
    @get:JsonProperty("type")
    val type: WorkItemType? = null,
    @get:JsonProperty("created")
    val created: kotlin.Long? = null,
    @get:JsonProperty("updated")
    val updated: kotlin.Long? = null,
    @get:JsonProperty("duration")
    val duration: DurationValue? = null,
    @get:JsonProperty("date")
    val date: kotlin.Long? = null,
    @get:JsonProperty("issue")
    val issue: Issue? = null,
    @get:JsonProperty("usesMarkdown")
    val usesMarkdown: kotlin.Boolean? = null,
    @get:JsonProperty("id")
    val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String? = null,
)

