/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.FieldStyle
import online.ecm.youtrack.model.Issue
import online.ecm.youtrack.model.IssueTagAllOf
import online.ecm.youtrack.model.User
import online.ecm.youtrack.model.UserGroup
import online.ecm.youtrack.model.WatchFolder

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents an issue tag.
 *
 * @param name 
 * @param id 
 * @param dollarType 
 * @param owner 
 * @param visibleFor 
 * @param updateableBy 
 * @param issues 
 * @param color 
 * @param untagOnResolve 
 */

data class IssueTag (

    @field:JsonProperty("name")
    override val name: kotlin.String? = null,

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("owner")
    override val owner: User? = null,

    @field:JsonProperty("visibleFor")
    override val visibleFor: UserGroup? = null,

    @field:JsonProperty("updateableBy")
    override val updateableBy: UserGroup? = null,

    @field:JsonProperty("issues")
    val issues: kotlin.collections.List<Issue>? = null,

    @field:JsonProperty("color")
    val color: FieldStyle? = null,

    @field:JsonProperty("untagOnResolve")
    val untagOnResolve: kotlin.Boolean? = null

) : WatchFolder(name, id, dollarType, owner, visibleFor, updateableBy)

