/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.FilterField
import online.ecm.youtrack.model.SwimlaneValue

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param `field` 
 * @param defaultCardType 
 * @param propertyValues 
 */

data class IssueBasedSwimlaneSettingsAllOf (

    @field:JsonProperty("field")
    val `field`: FilterField? = null,

    @field:JsonProperty("defaultCardType")
    val defaultCardType: SwimlaneValue? = null,

    @field:JsonProperty("values")
    val propertyValues: kotlin.collections.List<SwimlaneValue>? = null

)

