/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.Issue
import online.ecm.youtrack.model.IssueLinkType

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents issue links of a particular link type (for example, 'relates to').
 *
 * @param direction 
 * @param linkType 
 * @param issues 
 * @param trimmedIssues 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
open class IssueLink (

    @get:JsonProperty("direction")
    val direction: Direction? = null,
    @get:JsonProperty("linkType")
    val linkType: IssueLinkType? = null,
    @get:JsonProperty("issues")
    val issues: kotlin.collections.List<Issue>? = null,
    @get:JsonProperty("trimmedIssues")
    val trimmedIssues: kotlin.collections.List<Issue>? = null,
    @get:JsonProperty("id")
    val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String? = null
)

