/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents an issue folder, such as a project, a saved search, or a tag.
 *
 * @param name 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = IssueTag::class, name = "IssueTag"),
    JsonSubTypes.Type(value = Project::class, name = "Project"),
    JsonSubTypes.Type(value = SavedQuery::class, name = "SavedQuery"),
    JsonSubTypes.Type(value = WatchFolder::class, name = "WatchFolder")
)
open class IssueFolder (

    @get:JsonProperty("name")
    open val name: kotlin.String? = null,
    @get:JsonProperty("id")
    open val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    open val dollarType: kotlin.String? = null,
)

