/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents jabber settings for this YouTrack installation.
 *
 * @param isEnabled 
 * @param host 
 * @param port 
 * @param login 
 * @param serviceName 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
interface JabberSettings {

    @get:JsonProperty("isEnabled")
    val isEnabled: kotlin.Boolean?
    @get:JsonProperty("host")
    val host: kotlin.String?
    @get:JsonProperty("port")
    val port: kotlin.Int?
    @get:JsonProperty("login")
    val login: kotlin.String?
    @get:JsonProperty("serviceName")
    val serviceName: kotlin.String?
    @get:JsonProperty("id")
    val id: kotlin.String?
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String?
}

