/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.CommandLimitedVisibilityAllOf
import online.ecm.youtrack.model.User
import online.ecm.youtrack.model.UserGroup
import online.ecm.youtrack.model.Visibility

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents visibility limited to several users and/or groups.
 *
 * @param id 
 * @param dollarType 
 * @param permittedGroups 
 * @param permittedUsers 
 */

data class LimitedVisibility (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("permittedGroups")
    val permittedGroups: kotlin.collections.List<UserGroup>? = null,

    @field:JsonProperty("permittedUsers")
    val permittedUsers: kotlin.collections.List<User>? = null

) : Visibility(id, dollarType)

