/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.Issue
import online.ecm.youtrack.model.IssueCreatedActivityItemAllOf
import online.ecm.youtrack.model.MultiValueActivityItem

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents a change in the `issues` attribute of an IssueLink entity. That is, each issue has the `links` attribute that contains an array of IssueLink entities. Each of them represents a link between the target issue and a collection of issues. For example, a set of issues to which the target one is linked as \"Duplicated by\". The change in the list of these issues is represented by `LinksActivityItem` entity.
 *
 * @param id 
 * @param dollarType 
 * @param target 
 * @param removed 
 * @param added 
 */

data class LinksActivityItem (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("target")
    val target: Issue? = null,

    @field:JsonProperty("removed")
    val removed: kotlin.collections.List<Issue>? = null,

    @field:JsonProperty("added")
    val added: kotlin.collections.List<Issue>? = null

) : MultiValueActivityItem(id, dollarType)

