/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents the notification settings in the profile of the specific user.
 *
 * @param notifyOnOwnChanges 
 * @param jabberNotificationsEnabled 
 * @param emailNotificationsEnabled 
 * @param mentionNotificationsEnabled 
 * @param duplicateClusterNotificationsEnabled 
 * @param mailboxIntegrationNotificationsEnabled 
 * @param usePlainTextEmails 
 * @param autoWatchOnComment 
 * @param autoWatchOnCreate 
 * @param autoWatchOnVote 
 * @param autoWatchOnUpdate 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
open class NotificationsUserProfile (

    @get:JsonProperty("notifyOnOwnChanges")
    val notifyOnOwnChanges: kotlin.Boolean? = null,
    @get:JsonProperty("jabberNotificationsEnabled")
    val jabberNotificationsEnabled: kotlin.Boolean? = null,
    @get:JsonProperty("emailNotificationsEnabled")
    val emailNotificationsEnabled: kotlin.Boolean? = null,
    @get:JsonProperty("mentionNotificationsEnabled")
    val mentionNotificationsEnabled: kotlin.Boolean? = null,
    @get:JsonProperty("duplicateClusterNotificationsEnabled")
    val duplicateClusterNotificationsEnabled: kotlin.Boolean? = null,
    @get:JsonProperty("mailboxIntegrationNotificationsEnabled")
    val mailboxIntegrationNotificationsEnabled: kotlin.Boolean? = null,
    @get:JsonProperty("usePlainTextEmails")
    val usePlainTextEmails: kotlin.Boolean? = null,
    @get:JsonProperty("autoWatchOnComment")
    val autoWatchOnComment: kotlin.Boolean? = null,
    @get:JsonProperty("autoWatchOnCreate")
    val autoWatchOnCreate: kotlin.Boolean? = null,
    @get:JsonProperty("autoWatchOnVote")
    val autoWatchOnVote: kotlin.Boolean? = null,
    @get:JsonProperty("autoWatchOnUpdate")
    val autoWatchOnUpdate: kotlin.Boolean? = null,
    @get:JsonProperty("id")
    val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String? = null,
)

