/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.IssueCustomField
import online.ecm.youtrack.model.PeriodIssueCustomFieldAllOf
import online.ecm.youtrack.model.PeriodValue

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents the period field in the issue.
 *
 * @param id 
 * @param dollarType 
 * @param `value` 
 */

data class PeriodIssueCustomField (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("value")
    val `value`: PeriodValue? = null

) : IssueCustomField(id, dollarType)

