/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.CustomField
import online.ecm.youtrack.model.Project
import online.ecm.youtrack.model.ProjectCustomField

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents project settings for the period field.
 *
 * @param `field` 
 * @param project 
 * @param canBeEmpty 
 * @param emptyFieldText 
 * @param ordinal 
 * @param isPublic 
 * @param hasRunningJob 
 * @param id 
 * @param dollarType 
 */

data class PeriodProjectCustomField (

    @field:JsonProperty("field")
    override val `field`: CustomField? = null,

    @field:JsonProperty("project")
    override val project: Project? = null,

    @field:JsonProperty("canBeEmpty")
    override val canBeEmpty: kotlin.Boolean? = null,

    @field:JsonProperty("emptyFieldText")
    override val emptyFieldText: kotlin.String? = null,

    @field:JsonProperty("ordinal")
    override val ordinal: kotlin.Int? = null,

    @field:JsonProperty("isPublic")
    override val isPublic: kotlin.Boolean? = null,

    @field:JsonProperty("hasRunningJob")
    override val hasRunningJob: kotlin.Boolean? = null,

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null

) : ProjectCustomField(field, project, canBeEmpty, emptyFieldText, ordinal, isPublic, hasRunningJob, id, dollarType)

