/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.FilterField

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents a predefined field of the issue. Predefined fields are always present in an issue and             |cannot be customized in a project. For example, `project`, `created`,             |`updated`, `tags`, and so on.
 *
 * @param name 
 * @param id 
 * @param dollarType 
 */

data class PredefinedFilterField (

    @field:JsonProperty("name")
    override val name: kotlin.String? = null,

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null

) : FilterField

