/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.ColorCoding
import online.ecm.youtrack.model.ProjectBasedColorCodingAllOf
import online.ecm.youtrack.model.ProjectColor

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Lets you set a color for a card based on its project.
 *
 * @param id 
 * @param dollarType 
 * @param projectColors 
 */

data class ProjectBasedColorCoding (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("projectColors")
    val projectColors: kotlin.collections.List<ProjectColor>? = null

) : ColorCoding

