/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.CustomField
import online.ecm.youtrack.model.Project

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents custom field settings for the particular project.
 *
 * @param `field` 
 * @param project 
 * @param canBeEmpty 
 * @param emptyFieldText 
 * @param ordinal 
 * @param isPublic 
 * @param hasRunningJob 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = BuildProjectCustomField::class, name = "BuildProjectCustomField"),
    JsonSubTypes.Type(value = BundleProjectCustomField::class, name = "BundleProjectCustomField"),
    JsonSubTypes.Type(value = EnumProjectCustomField::class, name = "EnumProjectCustomField"),
    JsonSubTypes.Type(value = GroupProjectCustomField::class, name = "GroupProjectCustomField"),
    JsonSubTypes.Type(value = OwnedProjectCustomField::class, name = "OwnedProjectCustomField"),
    JsonSubTypes.Type(value = PeriodProjectCustomField::class, name = "PeriodProjectCustomField"),
    JsonSubTypes.Type(value = SimpleProjectCustomField::class, name = "SimpleProjectCustomField"),
    JsonSubTypes.Type(value = StateProjectCustomField::class, name = "StateProjectCustomField"),
    JsonSubTypes.Type(value = TextProjectCustomField::class, name = "TextProjectCustomField"),
    JsonSubTypes.Type(value = UserProjectCustomField::class, name = "UserProjectCustomField"),
    JsonSubTypes.Type(value = VersionProjectCustomField::class, name = "VersionProjectCustomField")
)
open class ProjectCustomField (

    @get:JsonProperty("field")
    open val `field`: CustomField? = null,
    @get:JsonProperty("project")
    open val project: Project? = null,
    @get:JsonProperty("canBeEmpty")
    open val canBeEmpty: kotlin.Boolean? = null,
    @get:JsonProperty("emptyFieldText")
    open val emptyFieldText: kotlin.String? = null,
    @get:JsonProperty("ordinal")
    open val ordinal: kotlin.Int? = null,
    @get:JsonProperty("isPublic")
    open val isPublic: kotlin.Boolean? = null,
    @get:JsonProperty("hasRunningJob")
    open val hasRunningJob: kotlin.Boolean? = null,
    @get:JsonProperty("id")
    open val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    open val dollarType: kotlin.String? = null,
)

