/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.IssueFolder
import online.ecm.youtrack.model.Suggestion

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents the list of search suggestions for the currently entered search query.
 *
 * @param caret 
 * @param ignoreUnresolvedSetting 
 * @param query 
 * @param suggestions 
 * @param folders 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
open class SearchSuggestions (

    @get:JsonProperty("caret")
    val caret: kotlin.Int? = null,
    @get:JsonProperty("ignoreUnresolvedSetting")
    val ignoreUnresolvedSetting: kotlin.Boolean? = null,
    @get:JsonProperty("query")
    val query: kotlin.String? = null,
    @get:JsonProperty("suggestions")
    val suggestions: kotlin.collections.List<Suggestion>? = null,
    @get:JsonProperty("folders")
    val folders: kotlin.collections.List<IssueFolder>? = null,
    @get:JsonProperty("id")
    val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String? = null,
)

