/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.SimpleValueActivityItemAllOf
import online.ecm.youtrack.model.SingleValueActivityItem

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents the change in attributes of a simple type in the target entity: Issue, IssueComment, WorkItem, IssueAttachment.
 *
 * @param id 
 * @param dollarType 
 * @param removed 
 * @param added 
 */

open class SimpleValueActivityItem (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("removed")
    open val removed: kotlin.Any? = null,

    @field:JsonProperty("added")
    open val added: kotlin.Any? = null

) : SingleValueActivityItem(id, dollarType)

