/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.CustomField
import online.ecm.youtrack.model.Sprint

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Describes sprints configuration.
 *
 * @param isExplicit 
 * @param cardOnSeveralSprints 
 * @param defaultSprint 
 * @param disableSprints 
 * @param explicitQuery 
 * @param sprintSyncField 
 * @param hideSubtasksOfCards 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
interface SprintsSettings {

    @get:JsonProperty("isExplicit")
    val isExplicit: kotlin.Boolean?
    @get:JsonProperty("cardOnSeveralSprints")
    val cardOnSeveralSprints: kotlin.Boolean?
    @get:JsonProperty("defaultSprint")
    val defaultSprint: Sprint?
    @get:JsonProperty("disableSprints")
    val disableSprints: kotlin.Boolean?
    @get:JsonProperty("explicitQuery")
    val explicitQuery: kotlin.String?
    @get:JsonProperty("sprintSyncField")
    val sprintSyncField: CustomField?
    @get:JsonProperty("hideSubtasksOfCards")
    val hideSubtasksOfCards: kotlin.Boolean?
    @get:JsonProperty("id")
    val id: kotlin.String?
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String?
}

