/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.Issue
import online.ecm.youtrack.model.Sprint

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param target 
 * @param removed 
 * @param added 
 */

data class SprintActivityItemAllOf (

    @field:JsonProperty("target")
    val target: Issue? = null,

    @field:JsonProperty("removed")
    val removed: kotlin.collections.List<Sprint>? = null,

    @field:JsonProperty("added")
    val added: kotlin.collections.List<Sprint>? = null

)

