/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents query suggestion.
 *
 * @param completionStart 
 * @param completionEnd 
 * @param matchingStart 
 * @param matchingEnd 
 * @param caret 
 * @param description 
 * @param option 
 * @param prefix 
 * @param suffix 
 * @param group 
 * @param icon 
 * @param auxiliaryIcon 
 * @param className 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
interface Suggestion {

    @get:JsonProperty("completionStart")
    val completionStart: kotlin.Int?
    @get:JsonProperty("completionEnd")
    val completionEnd: kotlin.Int?
    @get:JsonProperty("matchingStart")
    val matchingStart: kotlin.Int?
    @get:JsonProperty("matchingEnd")
    val matchingEnd: kotlin.Int?
    @get:JsonProperty("caret")
    val caret: kotlin.Int?
    @get:JsonProperty("description")
    val description: kotlin.String?
    @get:JsonProperty("option")
    val option: kotlin.String?
    @get:JsonProperty("prefix")
    val prefix: kotlin.String?
    @get:JsonProperty("suffix")
    val suffix: kotlin.String?
    @get:JsonProperty("group")
    val group: kotlin.String?
    @get:JsonProperty("icon")
    val icon: kotlin.String?
    @get:JsonProperty("auxiliaryIcon")
    val auxiliaryIcon: kotlin.String?
    @get:JsonProperty("className")
    val className: kotlin.String?
    @get:JsonProperty("id")
    val id: kotlin.String?
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String?
}

