/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents the System settings that affect core functionality of YouTrack.
 *
 * @param baseUrl 
 * @param maxUploadFileSize 
 * @param maxExportItems 
 * @param administratorEmail 
 * @param allowStatisticsCollection 
 * @param isApplicationReadOnly 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
interface SystemSettings {

    @get:JsonProperty("baseUrl")
    val baseUrl: kotlin.String?
    @get:JsonProperty("maxUploadFileSize")
    val maxUploadFileSize: kotlin.Long?
    @get:JsonProperty("maxExportItems")
    val maxExportItems: kotlin.Int?
    @get:JsonProperty("administratorEmail")
    val administratorEmail: kotlin.String?
    @get:JsonProperty("allowStatisticsCollection")
    val allowStatisticsCollection: kotlin.Boolean?
    @get:JsonProperty("isApplicationReadOnly")
    val isApplicationReadOnly: kotlin.Boolean?
    @get:JsonProperty("id")
    val id: kotlin.String?
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String?
}

