/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.CustomFieldActivityItem
import online.ecm.youtrack.model.Issue
import online.ecm.youtrack.model.TextCustomFieldActivityItemAllOf

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents an activity that affects a custom field of the `text` type of an issue.
 *
 * @param id 
 * @param dollarType 
 * @param target 
 * @param removed 
 * @param added 
 * @param markup 
 */

data class TextCustomFieldActivityItem (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("target")
    override val target: Issue? = null,

    @field:JsonProperty("removed")
    override val removed: kotlin.String? = null,

    @field:JsonProperty("added")
    override val added: kotlin.String? = null,

    @field:JsonProperty("markup")
    val markup: kotlin.String? = null

) : CustomFieldActivityItem(id, dollarType, target, removed, added)

