/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.SimpleValueActivityItem
import online.ecm.youtrack.model.TextMarkupActivityItemAllOf

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents a change in a `String`-type attribute with the support of markup: `description` in an Issue or IssueWorkItem, and the `text` of the IssueComment. This entity lets you get the rendered text after the change.
 *
 * @param id 
 * @param dollarType 
 * @param removed 
 * @param added 
 * @param markup 
 */

data class TextMarkupActivityItem (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("removed")
    override val removed: kotlin.String? = null,

    @field:JsonProperty("added")
    override val added: kotlin.String? = null,

    @field:JsonProperty("markup")
    val markup: kotlin.String? = null

) : SimpleValueActivityItem(id, dollarType, removed, added)

