/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.IssueCustomField
import online.ecm.youtrack.model.TextFieldValue
import online.ecm.youtrack.model.TextIssueCustomFieldAllOf

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents the issue custom field of the `text` type.
 *
 * @param id 
 * @param dollarType 
 * @param `value` 
 */

data class TextIssueCustomField (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("value")
    val `value`: TextFieldValue? = null

) : IssueCustomField(id, dollarType)

