/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.IssueTag
import online.ecm.youtrack.model.SavedQuery
import online.ecm.youtrack.model.UserProfiles

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents a user in YouTrack. Please note that the read-only properties of a user account, like              credentials, or email and so on, you can only change in               <a href=\"https://www.jetbrains.com/help/youtrack/devportal/? = null,Hub-REST-API\">Hub REST API</a>.
 *
 * @param login 
 * @param fullName 
 * @param email 
 * @param jabberAccountName 
 * @param ringId 
 * @param guest 
 * @param online 
 * @param banned 
 * @param tags 
 * @param savedQueries 
 * @param avatarUrl 
 * @param profiles 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = Me::class, name = "Me"),
    JsonSubTypes.Type(value = VcsUnresolvedUser::class, name = "VcsUnresolvedUser")
)
open class User (

    @get:JsonProperty("login")
    open val login: kotlin.String? = null,
    @get:JsonProperty("fullName")
    open val fullName: kotlin.String? = null,
    @get:JsonProperty("email")
    open val email: kotlin.String? = null,
    @get:JsonProperty("jabberAccountName")
    open val jabberAccountName: kotlin.String? = null,
    @get:JsonProperty("ringId")
    open val ringId: kotlin.String? = null,
    @get:JsonProperty("guest")
    open val guest: kotlin.Boolean? = null,
    @get:JsonProperty("online")
    open val online: kotlin.Boolean? = null,
    @get:JsonProperty("banned")
    open val banned: kotlin.Boolean? = null,
    @get:JsonProperty("tags")
    open val tags: kotlin.collections.List<IssueTag>? = null,
    @get:JsonProperty("savedQueries")
    open val savedQueries: kotlin.collections.List<SavedQuery>? = null,
    @get:JsonProperty("avatarUrl")
    open val avatarUrl: kotlin.String? = null,
    @get:JsonProperty("profiles")
    open val profiles: UserProfiles? = null,
    @get:JsonProperty("id")
    open val id: kotlin.String? = null,
    @get:JsonProperty("\$type")
    open val dollarType: kotlin.String? = null,
)

