/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.Bundle
import online.ecm.youtrack.model.User
import online.ecm.youtrack.model.UserBundleAllOf
import online.ecm.youtrack.model.UserGroup

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents a set of values that contains users. You can add to the set both individual user accounts and groups of users.
 *
 * @param isUpdateable 
 * @param id 
 * @param dollarType 
 * @param groups 
 * @param individuals 
 * @param aggregatedUsers 
 */

data class UserBundle (

    @field:JsonProperty("isUpdateable")
    override val isUpdateable: kotlin.Boolean? = null,

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("groups")
    val groups: kotlin.collections.List<UserGroup>? = null,

    @field:JsonProperty("individuals")
    val individuals: kotlin.collections.List<User>? = null,

    @field:JsonProperty("aggregatedUsers")
    val aggregatedUsers: kotlin.collections.List<User>? = null

) : Bundle(isUpdateable, id, dollarType)

