/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.User
import online.ecm.youtrack.model.UserGroup

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param groups 
 * @param individuals 
 * @param aggregatedUsers 
 */

data class UserBundleAllOf (

    @field:JsonProperty("groups")
    val groups: kotlin.collections.List<UserGroup>? = null,

    @field:JsonProperty("individuals")
    val individuals: kotlin.collections.List<User>? = null,

    @field:JsonProperty("aggregatedUsers")
    val aggregatedUsers: kotlin.collections.List<User>? = null

)

