/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.Project

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Represents a group of users.
 *
 * @param name 
 * @param ringId 
 * @param usersCount 
 * @param icon 
 * @param allUsersGroup 
 * @param teamForProject 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
interface UserGroup {

    @get:JsonProperty("name")
    val name: kotlin.String?
    @get:JsonProperty("ringId")
    val ringId: kotlin.String?
    @get:JsonProperty("usersCount")
    val usersCount: kotlin.Long?
    @get:JsonProperty("icon")
    val icon: kotlin.String?
    @get:JsonProperty("allUsersGroup")
    val allUsersGroup: kotlin.Boolean?
    @get:JsonProperty("teamForProject")
    val teamForProject: Project?
    @get:JsonProperty("id")
    val id: kotlin.String?
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String?
}

