/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.SimpleValueActivityItem
import online.ecm.youtrack.model.UsesMarkupActivityItemAllOf

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents the change of the boolean flag that indicates whether YouTrack Wiki or Markdown is used in the target entity as a markup language. If \"true\", then the markdown is used. Otherwise, YouTrack Wiki markup.
 *
 * @param id 
 * @param dollarType 
 * @param removed 
 * @param added 
 * @param markup 
 */

data class UsesMarkupActivityItem (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("removed")
    override val removed: kotlin.Boolean? = null,

    @field:JsonProperty("added")
    override val added: kotlin.Boolean? = null,

    @field:JsonProperty("markup")
    val markup: kotlin.String? = null

) : SimpleValueActivityItem(id, dollarType, removed, added)

