/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.User

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param removed 
 * @param added 
 * @param author 
 */

data class VcsChangeActivityItemAllOf (

    @field:JsonProperty("removed")
    val removed: kotlin.Any? = null,

    @field:JsonProperty("added")
    val added: kotlin.Any? = null,

    @field:JsonProperty("author")
    val author: User? = null

)

