/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.IssueTag
import online.ecm.youtrack.model.SavedQuery
import online.ecm.youtrack.model.User
import online.ecm.youtrack.model.UserProfiles
import online.ecm.youtrack.model.VcsUnresolvedUserAllOf

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents an author of a VCS change that could not be found in the list of YouTrack users.
 *
 * @param login 
 * @param fullName 
 * @param email 
 * @param jabberAccountName 
 * @param ringId 
 * @param guest 
 * @param online 
 * @param banned 
 * @param tags 
 * @param savedQueries 
 * @param avatarUrl 
 * @param profiles 
 * @param id 
 * @param dollarType 
 * @param name 
 */

data class VcsUnresolvedUser (

    @field:JsonProperty("login")
    override val login: kotlin.String? = null,

    @field:JsonProperty("fullName")
    override val fullName: kotlin.String? = null,

    @field:JsonProperty("email")
    override val email: kotlin.String? = null,

    @field:JsonProperty("jabberAccountName")
    override val jabberAccountName: kotlin.String? = null,

    @field:JsonProperty("ringId")
    override val ringId: kotlin.String? = null,

    @field:JsonProperty("guest")
    override val guest: kotlin.Boolean? = null,

    @field:JsonProperty("online")
    override val online: kotlin.Boolean? = null,

    @field:JsonProperty("banned")
    override val banned: kotlin.Boolean? = null,

    @field:JsonProperty("tags")
    override val tags: kotlin.collections.List<IssueTag>? = null,

    @field:JsonProperty("savedQueries")
    override val savedQueries: kotlin.collections.List<SavedQuery>? = null,

    @field:JsonProperty("avatarUrl")
    override val avatarUrl: kotlin.String? = null,

    @field:JsonProperty("profiles")
    override val profiles: UserProfiles? = null,

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null

) : User(
    login,
    fullName,
    email,
    jabberAccountName,
    ringId,
    guest,
    online,
    banned,
    tags,
    savedQueries,
    avatarUrl,
    profiles,
    id,
    dollarType
)

