/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.User

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param targetMember 
 * @param targetSubMember 
 * @param removed 
 * @param added 
 */

data class VisibilityUserActivityItemAllOf (

    @field:JsonProperty("targetMember")
    val targetMember: kotlin.String? = null,

    @field:JsonProperty("targetSubMember")
    val targetSubMember: kotlin.String? = null,

    @field:JsonProperty("removed")
    val removed: kotlin.collections.List<User>? = null,

    @field:JsonProperty("added")
    val added: kotlin.collections.List<User>? = null

)

