/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.UserGroup
import online.ecm.youtrack.model.VisibilityActivityItem
import online.ecm.youtrack.model.VisibilityGroupActivityItemAllOf

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents the event when a user adds or removes a group to/from the Visibility settings of the target entity.
 *
 * @param id 
 * @param dollarType 
 * @param targetMember 
 * @param targetSubMember 
 * @param removed 
 * @param added 
 */

data class VisibilityGroupActivityItem (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("targetMember")
    override val targetMember: kotlin.String? = null,

    @field:JsonProperty("targetSubMember")
    val targetSubMember: kotlin.String? = null,

    @field:JsonProperty("removed")
    val removed: kotlin.collections.List<UserGroup>? = null,

    @field:JsonProperty("added")
    val added: kotlin.collections.List<UserGroup>? = null

) : VisibilityActivityItem(id, dollarType, targetMember)

