/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.MultiValueActivityItem
import online.ecm.youtrack.model.VisibilityActivityItemAllOf

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents the changes of properties responsible for visibility restriction. Can be <a href=\"api-entity-VisibilityGroupActivityItem.xml\">VisibilityGroupActivityItem</a> or <a href=\"api-entity-VisibilityUserActivityItem.xml\">VisibilityUserActivityItem</a>
 *
 * @param id 
 * @param dollarType 
 * @param targetMember 
 */

open class VisibilityActivityItem (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("targetMember")
    open val targetMember: kotlin.String? = null

) : MultiValueActivityItem(id, dollarType)

