/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.IssueFolder
import online.ecm.youtrack.model.User
import online.ecm.youtrack.model.UserGroup
import online.ecm.youtrack.model.WatchFolderAllOf

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A `WatchFolder` is an `IssueFolder` that let you enable notifications for a set  of issues that it enfolds. It is a common abstract ancestor for saved searches and issue tags.
 *
 * @param name 
 * @param id 
 * @param dollarType 
 * @param owner 
 * @param visibleFor 
 * @param updateableBy 
 */

open class WatchFolder (

    @field:JsonProperty("name")
    override val name: kotlin.String? = null,

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("owner")
    open val owner: User? = null,

    @field:JsonProperty("visibleFor")
    open val visibleFor: UserGroup? = null,

    @field:JsonProperty("updateableBy")
    open val updateableBy: UserGroup? = null

) : IssueFolder(name, id, dollarType)

