/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Work schedule settings.
 *
 * @param minutesADay 
 * @param workDays 
 * @param firstDayOfWeek 
 * @param daysAWeek 
 * @param id 
 * @param dollarType 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "\$type", visible = true)
@JsonSubTypes(
)
interface WorkTimeSettings {

    @get:JsonProperty("minutesADay")
    val minutesADay: kotlin.Int?
    @get:JsonProperty("workDays")
    val workDays: kotlin.Int?
    @get:JsonProperty("firstDayOfWeek")
    val firstDayOfWeek: kotlin.Int?
    @get:JsonProperty("daysAWeek")
    val daysAWeek: kotlin.Int?
    @get:JsonProperty("id")
    val id: kotlin.String?
    @get:JsonProperty("\$type")
    val dollarType: kotlin.String?
}

