/**
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package online.ecm.youtrack.model

import online.ecm.youtrack.model.DurationValue
import online.ecm.youtrack.model.IssueWorkItem
import online.ecm.youtrack.model.SingleValueActivityItem
import online.ecm.youtrack.model.WorkItemDurationActivityItemAllOf

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Represents a change in the `duration` attribute of a work item.
 *
 * @param id 
 * @param dollarType 
 * @param target 
 * @param removed 
 * @param added 
 */

data class WorkItemDurationActivityItem (

    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    @field:JsonProperty("\$type")
    override val dollarType: kotlin.String? = null,

    @field:JsonProperty("target")
    val target: IssueWorkItem? = null,

    @field:JsonProperty("removed")
    val removed: DurationValue? = null,

    @field:JsonProperty("added")
    val added: DurationValue? = null

) : SingleValueActivityItem(id, dollarType)

